#+TITLE: JASA - Just Another Slack API
#+AUTHOR: dptd

* Installation
=git clone https://github.com/dptd/jasa=

=(ql:quickload :jasa)=

* Usage
JASA follows official [[https://api.slack.com/methods/][Slack Web API]] methods convention. You should be able to specify all the arguments described in the Slack API for method which is implemented. For example for [[https://api.slack.com/methods/chat.postMessage][chat.postMessage]] there are plenty of different methods available. Most of the time you can set them using Common Lisp keywords.

*** How to post messages to specific channel.
#+BEGIN_SRC lisp
(jasa.chat:post-message :token "YourSlackAPIToken"
                        :channel "C01234567"
                        :text "test message")

(jasa.chat:post-message :token "YourSlackAPIToken"
                        :channel "C01234567"
                        :text "test message"
                        :icon_emoji ":robot_face:")
#+END_SRC

You can also use [[https://api.slack.com/docs/message-attachments][message attachments]] by calling =(prepare-attachments)= function.

#+BEGIN_SRC lisp
(jasa.chat:post-message :token "YourSlackAPIToken"
                        :channel "C01234567"
                        :attachments (jasa.chat:prepare-attachments :pretext "Structured Message"
                                                                    :text "Hello there!"
                                                                    :color "#36a64f"))
#+END_SRC

If you want you can also provide raw json yourself.

#+BEGIN_SRC lisp
(jasa.chat:post-message :token "YourSlackAPIToken"
                        :channel "C01234567"
                        :attachments "[{\"pretext\":\"Structured Message\",\"text\":\"Hello there!\",\"color\":\"#36a64f\"}]")
#+END_SRC

*** How to get information about direct messages.
#+BEGIN_SRC lisp
(jasa.im:list-im :token "YourSlackAPIToken")
#+END_SRC

*** How to get messages from specific direct messages channel.
#+BEGIN_SRC lisp
(jasa.im:history :token "YourSlackAPIToken"
                 :channel "D01234567"
                 :count "2")

(jasa.im:history :token "YourSlackAPIToken"
                 :channel "D01234567"
                 :latest "UnixTimeStamp")
#+END_SRC

* API
** jasa
=(jasa:*token*)=
** jasa.core
=(jasa:send)=

=(jasa:send-and-get-answer)=
** jasa.api
=(jasa.api:test)=
** jasa.auth
=(jasa.auth:test)=

=(jasa.auth:revoke)=
** jasa.bots
=(jasa.bots:info)=
** jasa.chat
=(jasa.chat:post-message)=

=(jasa.chat:prepare-attachments)=
** jasa.im
=(jasa.im:close-im)=

=(jasa.im:history)=

=(jasa.im:list-im)=

=(jasa.im:mark)=

=(jasa.im:open-im)=
** jasa.emoji
=(jasa.emoji:list-emoji)=
** jasa.channels
=(jasa.channels:history)= (implementation ongoing)
=(jasa.channels:info)= (implementation ongoing)
** jasa.users
=(jasa.users:info)= (implementaiton ongoing)
